//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAMP.Utility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LAMPMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LAMPMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LAMP.Utility.LAMPMessages", typeof(LAMPMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This administrator account does not exist in the website..
        /// </summary>
        internal static string ADMIN_NOT_REGISTERED {
            get {
                return ResourceManager.GetString("ADMIN_NOT_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This administrator account already exists in the website..
        /// </summary>
        internal static string ADMIN_NOT_SAVED {
            get {
                return ResourceManager.GetString("ADMIN_NOT_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The administrator account has been created successfully..
        /// </summary>
        internal static string ADMIN_SAVED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("ADMIN_SAVED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The administrator account has been updated successfully..
        /// </summary>
        internal static string ADMIN_UPDATED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("ADMIN_UPDATED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app help has been saved successfully..
        /// </summary>
        internal static string APP_HELP_SAVED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("APP_HELP_SAVED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app help has been updated successfully..
        /// </summary>
        internal static string APP_HELP_UPDATED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("APP_HELP_UPDATED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The article has been saved successfully..
        /// </summary>
        internal static string BLOG_SAVED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("BLOG_SAVED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The article has been updated successfully..
        /// </summary>
        internal static string BLOG_UPDATED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("BLOG_UPDATED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The distraction survey has been saved successfully..
        /// </summary>
        internal static string DISTRACTION_SURVEY_SAVED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("DISTRACTION_SURVEY_SAVED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred. Please try again later..
        /// </summary>
        internal static string Err_2030 {
            get {
                return ResourceManager.GetString("Err_2030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input data..
        /// </summary>
        internal static string Err_2031 {
            get {
                return ResourceManager.GetString("Err_2031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the session token..
        /// </summary>
        internal static string Err_2033 {
            get {
                return ResourceManager.GetString("Err_2033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed. Please check the specified credentials..
        /// </summary>
        internal static string Err_2034 {
            get {
                return ResourceManager.GetString("Err_2034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User name..
        /// </summary>
        internal static string Err_2035 {
            get {
                return ResourceManager.GetString("Err_2035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You seem to have already registered..
        /// </summary>
        internal static string Err_2036 {
            get {
                return ResourceManager.GetString("Err_2036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired..
        /// </summary>
        internal static string Err_2037 {
            get {
                return ResourceManager.GetString("Err_2037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User..
        /// </summary>
        internal static string Err_2040 {
            get {
                return ResourceManager.GetString("Err_2040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address already exists. Use another one..
        /// </summary>
        internal static string Err_2041 {
            get {
                return ResourceManager.GetString("Err_2041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email ID..
        /// </summary>
        internal static string Err_2042 {
            get {
                return ResourceManager.GetString("Err_2042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image..
        /// </summary>
        internal static string Err_2043 {
            get {
                return ResourceManager.GetString("Err_2043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user has been deactivated. Please contact the administrator..
        /// </summary>
        internal static string Err_2044 {
            get {
                return ResourceManager.GetString("Err_2044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Password..
        /// </summary>
        internal static string Err_2045 {
            get {
                return ResourceManager.GetString("Err_2045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Current Password..
        /// </summary>
        internal static string Err_2046 {
            get {
                return ResourceManager.GetString("Err_2046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify your Old Password correctly..
        /// </summary>
        internal static string Err_2047 {
            get {
                return ResourceManager.GetString("Err_2047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User..
        /// </summary>
        internal static string Err_2048 {
            get {
                return ResourceManager.GetString("Err_2048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date Of Birth.
        /// </summary>
        internal static string Err_2049 {
            get {
                return ResourceManager.GetString("Err_2049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account has been deleted..
        /// </summary>
        internal static string Err_2050 {
            get {
                return ResourceManager.GetString("Err_2050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This study id already exists. Use another one..
        /// </summary>
        internal static string Err_2051 {
            get {
                return ResourceManager.GetString("Err_2051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the registered email address correctly..
        /// </summary>
        internal static string MAIL_CANNOT_SEND {
            get {
                return ResourceManager.GetString("MAIL_CANNOT_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmPasswordMessage.
        /// </summary>
        internal static string MSG_CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest user has been registered successfully..
        /// </summary>
        internal static string MSG_GUEST_USER_REGISTERED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_GUEST_USER_REGISTERED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials..
        /// </summary>
        internal static string MSG_INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("MSG_INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a valid email address..
        /// </summary>
        internal static string MSG_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("MSG_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewPasswordMessage.
        /// </summary>
        internal static string MSG_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("MSG_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully..
        /// </summary>
        internal static string MSG_PASSWORD_CHANGED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_PASSWORD_CHANGED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A link to reset your password has been sent to your email address..
        /// </summary>
        internal static string MSG_RESET_PASSWORD_LINK_EMAIL_SEND {
            get {
                return ResourceManager.GetString("MSG_RESET_PASSWORD_LINK_EMAIL_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session token has been updated successfully..
        /// </summary>
        internal static string MSG_SESSIONTOKEN_UPDATED {
            get {
                return ResourceManager.GetString("MSG_SESSIONTOKEN_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Confirm Password..
        /// </summary>
        internal static string MSG_SPECIFY_CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("MSG_SPECIFY_CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Current Password..
        /// </summary>
        internal static string MSG_SPECIFY_CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("MSG_SPECIFY_CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password and New Password entries must not match..
        /// </summary>
        internal static string MSG_SPECIFY_DIFFERENT_PASSWORDS {
            get {
                return ResourceManager.GetString("MSG_SPECIFY_DIFFERENT_PASSWORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Email Address..
        /// </summary>
        internal static string MSG_SPECIFY_EMAIL_ADDRESS {
            get {
                return ResourceManager.GetString("MSG_SPECIFY_EMAIL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify New Password..
        /// </summary>
        internal static string MSG_SPECIFY_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("MSG_SPECIFY_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Password..
        /// </summary>
        internal static string MSG_SPECIFY_PASSWORD {
            get {
                return ResourceManager.GetString("MSG_SPECIFY_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password and Confirm Password entries must be the same..
        /// </summary>
        internal static string MSG_SPECIFY_SAME_PASSWORDS {
            get {
                return ResourceManager.GetString("MSG_SPECIFY_SAME_PASSWORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This question cannot be deleted as at least one question has to be maintained in the survey..
        /// </summary>
        internal static string MSG_SURVEY_QUESTIONS_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_SURVEY_QUESTIONS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified Survey Name is already in use. Enter another..
        /// </summary>
        internal static string MSG_SURVEY_SAVE_FAILED {
            get {
                return ResourceManager.GetString("MSG_SURVEY_SAVE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The survey has been saved successfully..
        /// </summary>
        internal static string MSG_SURVEY_SAVED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_SURVEY_SAVED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user details have been saved successfully..
        /// </summary>
        internal static string MSG_USER_DETAILS_SAVED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_USER_DETAILS_SAVED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All user details, except the clinical profile image, have been saved successfully..
        /// </summary>
        internal static string MSG_USER_DETAILS_SAVED_SUCCESSFULLY_IMAGE_NOT_SAVED {
            get {
                return ResourceManager.GetString("MSG_USER_DETAILS_SAVED_SUCCESSFULLY_IMAGE_NOT_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has logged in successfully..
        /// </summary>
        internal static string MSG_USER_LOGGED_IN_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_USER_LOGGED_IN_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been sent to your registered email address..
        /// </summary>
        internal static string MSG_USER_PASSWORD_SEND_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_USER_PASSWORD_SEND_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has been registered successfully..
        /// </summary>
        internal static string MSG_USER_REGISTERED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_USER_REGISTERED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user settings have been saved successfully..
        /// </summary>
        internal static string MSG_USER_SETTING_SAVED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_USER_SETTING_SAVED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user&apos;s survey details have been saved successfully..
        /// </summary>
        internal static string MSG_USER_SURVEY_DETAILS_FETCHED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_USER_SURVEY_DETAILS_FETCHED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user&apos;s survey questions and answers have been fetched successfully..
        /// </summary>
        internal static string MSG_USER_SURVEY_QUE_ANS_FETCHED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_USER_SURVEY_QUE_ANS_FETCHED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user&apos;s survey has been saved successfully..
        /// </summary>
        internal static string MSG_USER_SURVEY_SAVED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_USER_SURVEY_SAVED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user survey and game schedule have been saved successfully..
        /// </summary>
        internal static string SCHEDULE_SAVED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("SCHEDULE_SAVED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user survey and game schedule have been updated successfully..
        /// </summary>
        internal static string SCHEDULE_UPDATED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("SCHEDULE_UPDATED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tip has been saved successfully..
        /// </summary>
        internal static string TIP_SAVED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("TIP_SAVED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This admin has not yet registered in the website..
        /// </summary>
        internal static string UN_REGISTERED_ADMIN_MESSAGE {
            get {
                return ResourceManager.GetString("UN_REGISTERED_ADMIN_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user has not yet registered in the mobile app..
        /// </summary>
        internal static string UN_REGISTERED_USER_MESSAGE {
            get {
                return ResourceManager.GetString("UN_REGISTERED_USER_MESSAGE", resourceCulture);
            }
        }
    }
}
