//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAMP.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_JewelsTrailsASettings
    {
        public long AdminJTASettingID { get; set; }
        public Nullable<long> AdminID { get; set; }
        public Nullable<int> NoOfSeconds_Beg { get; set; }
        public Nullable<int> NoOfSeconds_Int { get; set; }
        public Nullable<int> NoOfSeconds_Adv { get; set; }
        public Nullable<int> NoOfSeconds_Exp { get; set; }
        public Nullable<int> NoOfDiamonds { get; set; }
        public Nullable<int> NoOfShapes { get; set; }
        public Nullable<int> NoOfBonusPoints { get; set; }
        public Nullable<int> X_NoOfChangesInLevel { get; set; }
        public Nullable<int> X_NoOfDiamonds { get; set; }
        public Nullable<int> Y_NoOfChangesInLevel { get; set; }
        public Nullable<int> Y_NoOfShapes { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
