//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAMP.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Settings
    {
        public long AdminSettingID { get; set; }
        public Nullable<long> AdminID { get; set; }
        public Nullable<long> ReminderClearInterval { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
