//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAMP.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppHelp
    {
        public long HelpID { get; set; }
        public string HelpTitle { get; set; }
        public string HelpText { get; set; }
        public string Content { get; set; }
        public string ImageURL { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> EditedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> AdminID { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
