//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAMP.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTest_ScratchImage
    {
        public CTest_ScratchImage()
        {
            this.CTest_ScratchImageResult = new HashSet<CTest_ScratchImageResult>();
        }
    
        public long ScratchImageID { get; set; }
        public string FigureName { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual ICollection<CTest_ScratchImageResult> CTest_ScratchImageResult { get; set; }
    }
}
