//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAMP.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTest_TrailsBResultDtl
    {
        public long TrailsBResultDtlID { get; set; }
        public long TrailsBResultID { get; set; }
        public string Alphabet { get; set; }
        public string TimeTaken { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual CTest_TrailsBResult CTest_TrailsBResult { get; set; }
    }
}
