//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAMP.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTest_SpinWheelResult
    {
        public long SpinWheelResultID { get; set; }
        public long UserID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string CollectedStars { get; set; }
        public Nullable<int> DayStreak { get; set; }
        public Nullable<byte> StrakSpin { get; set; }
        public Nullable<System.DateTime> GameDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
