//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAMP.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthKit_DailyValues
    {
        public long HKDailyValueID { get; set; }
        public long UserID { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string HeartRate { get; set; }
        public string BloodPressure { get; set; }
        public string RespiratoryRate { get; set; }
        public string Sleep { get; set; }
        public string Steps { get; set; }
        public string FlightClimbed { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> EditedOn { get; set; }
        public string Segment { get; set; }
        public string Distance { get; set; }
    
        public virtual User User { get; set; }
    }
}
