//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAMP.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthKit_Parameters
    {
        public HealthKit_Parameters()
        {
            this.HealthKit_ParamValues = new HashSet<HealthKit_ParamValues>();
        }
    
        public long HKParamID { get; set; }
        public string HKParamName { get; set; }
    
        public virtual ICollection<HealthKit_ParamValues> HealthKit_ParamValues { get; set; }
    }
}
