//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAMP.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repeat
    {
        public Repeat()
        {
            this.Admin_BatchSchedule = new HashSet<Admin_BatchSchedule>();
            this.Admin_CTestSchedule = new HashSet<Admin_CTestSchedule>();
            this.Admin_SurveySchedule = new HashSet<Admin_SurveySchedule>();
            this.UserSettings = new HashSet<UserSetting>();
            this.UserSettings1 = new HashSet<UserSetting>();
        }
    
        public long RepeatID { get; set; }
        public string RepeatInterval { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<Admin_BatchSchedule> Admin_BatchSchedule { get; set; }
        public virtual ICollection<Admin_CTestSchedule> Admin_CTestSchedule { get; set; }
        public virtual ICollection<Admin_SurveySchedule> Admin_SurveySchedule { get; set; }
        public virtual ICollection<UserSetting> UserSettings { get; set; }
        public virtual ICollection<UserSetting> UserSettings1 { get; set; }
    }
}
