//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAMP.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyResult
    {
        public SurveyResult()
        {
            this.SurveyResultDtls = new HashSet<SurveyResultDtl>();
        }
    
        public long SurveyResultID { get; set; }
        public long UserID { get; set; }
        public byte SurveyType { get; set; }
        public string SurveyName { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Rating { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> Point { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<bool> IsDistraction { get; set; }
        public Nullable<bool> IsNotificationGame { get; set; }
        public Nullable<long> AdminBatchSchID { get; set; }
        public string SpinWheelScore { get; set; }
        public Nullable<long> SurveyID { get; set; }
    
        public virtual Admin_BatchSchedule Admin_BatchSchedule { get; set; }
        public virtual Survey Survey { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<SurveyResultDtl> SurveyResultDtls { get; set; }
    }
}
