//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAMP.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        public Survey()
        {
            this.Admin_CTestSurveySettings = new HashSet<Admin_CTestSurveySettings>();
            this.Admin_SurveySchedule = new HashSet<Admin_SurveySchedule>();
            this.SurveyQuestions = new HashSet<SurveyQuestion>();
            this.SurveyResults = new HashSet<SurveyResult>();
        }
    
        public long SurveyID { get; set; }
        public string SurveyName { get; set; }
        public Nullable<long> AdminID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> EditedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Language { get; set; }
    
        public virtual ICollection<Admin_CTestSurveySettings> Admin_CTestSurveySettings { get; set; }
        public virtual ICollection<Admin_SurveySchedule> Admin_SurveySchedule { get; set; }
        public virtual ICollection<SurveyQuestion> SurveyQuestions { get; set; }
        public virtual ICollection<SurveyResult> SurveyResults { get; set; }
    }
}
