//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAMP.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyResultDtl
    {
        public long SurveyResultDtlID { get; set; }
        public long SurveyResultID { get; set; }
        public string Question { get; set; }
        public string CorrectAnswer { get; set; }
        public string EnteredAnswer { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> TimeTaken { get; set; }
        public string ClickRange { get; set; }
    
        public virtual SurveyResult SurveyResult { get; set; }
    }
}
