//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAMP.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetting
    {
        public long UserSettingID { get; set; }
        public long UserID { get; set; }
        public string AppColor { get; set; }
        public Nullable<long> SympSurvey_SlotID { get; set; }
        public Nullable<System.DateTime> SympSurvey_Time { get; set; }
        public Nullable<long> SympSurvey_RepeatID { get; set; }
        public Nullable<long> CognTest_SlotID { get; set; }
        public Nullable<System.DateTime> CognTest_Time { get; set; }
        public Nullable<long> CognTest_RepeatID { get; set; }
        public string C24By7ContactNo { get; set; }
        public string PersonalHelpline { get; set; }
        public string PrefferedSurveys { get; set; }
        public string PrefferedCognitions { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> EditedOn { get; set; }
        public Nullable<bool> Protocol { get; set; }
        public Nullable<System.DateTime> BlogsViewedOn { get; set; }
        public Nullable<System.DateTime> TipsViewedOn { get; set; }
        public Nullable<System.DateTime> ProtocolDate { get; set; }
        public string Language { get; set; }
    
        public virtual Repeat Repeat { get; set; }
        public virtual Repeat Repeat1 { get; set; }
        public virtual Slot Slot { get; set; }
        public virtual Slot Slot1 { get; set; }
        public virtual User User { get; set; }
    }
}
